title: Now Plain Zero!
author: Ben Richards
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  By 2017, the world economy has collapsed. Food, natural resources and oil are in short supply.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
